version: '3.8'

services:
  postgres:
    container_name: HW11_postgres  # Ім'я контейнера
    image: postgres:16.1  # Образ PostgreSQL з версією 16.1
    environment:
      POSTGRES_USER: ${POSTGRES_USER}  # Логін користувача
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}  # Пароль користувача
      POSTGRES_DB: ${POSTGRES_DB}  # Назва бази даних
      PGDATA: /var/lib/postgresql/data/pgdata  # Шлях для даних
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"  # Мапінг портів
    volumes:
      - pgdata:/var/lib/postgresql/data    # Volume для зберігання даних

  pgadmin:
    container_name: HW11_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}  # Логін для pgAdmin
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}  # Пароль для pgAdmin
    ports:
      - "5050:80"  # Мапінг портів для pgAdmin (локальний порт -> контейнер)
    depends_on:
      - postgres  # pgAdmin залежить від сервісу PostgreSQL
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  web:
    container_name: HW11_web
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}

volumes:
  pgdata:
    driver: local  # Створення локального volume для зберігання даних PostgreSQL
  pgadmin_data:
    driver: local  # Volume для зберігання даних pgAdmin
